// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v7.34.1
// source: gopay_app.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GopayAppService_GetActionCatalog_FullMethodName        = "/gopay_app.GopayAppService/GetActionCatalog"
	GopayAppService_GetGopayAccount_FullMethodName         = "/gopay_app.GopayAppService/GetGopayAccount"
	GopayAppService_ListGopayAccounts_FullMethodName       = "/gopay_app.GopayAppService/ListGopayAccounts"
	GopayAppService_LoadGopayAccountState_FullMethodName   = "/gopay_app.GopayAppService/LoadGopayAccountState"
	GopayAppService_SaveGopayAccountState_FullMethodName   = "/gopay_app.GopayAppService/SaveGopayAccountState"
	GopayAppService_DeleteGopayAccount_FullMethodName      = "/gopay_app.GopayAppService/DeleteGopayAccount"
	GopayAppService_GetGopayAccountProfile_FullMethodName  = "/gopay_app.GopayAppService/GetGopayAccountProfile"
	GopayAppService_SaveGopayAccountProfile_FullMethodName = "/gopay_app.GopayAppService/SaveGopayAccountProfile"
	GopayAppService_GenerateDeviceProxy_FullMethodName     = "/gopay_app.GopayAppService/GenerateDeviceProxy"
	GopayAppService_CheckPhone_FullMethodName              = "/gopay_app.GopayAppService/CheckPhone"
	GopayAppService_ChangePhoneStart_FullMethodName        = "/gopay_app.GopayAppService/ChangePhoneStart"
	GopayAppService_ChangePhoneRetry_FullMethodName        = "/gopay_app.GopayAppService/ChangePhoneRetry"
	GopayAppService_ChangePhoneComplete_FullMethodName     = "/gopay_app.GopayAppService/ChangePhoneComplete"
	GopayAppService_DeactivateStart_FullMethodName         = "/gopay_app.GopayAppService/DeactivateStart"
	GopayAppService_DeactivateComplete_FullMethodName      = "/gopay_app.GopayAppService/DeactivateComplete"
	GopayAppService_LoginStart_FullMethodName              = "/gopay_app.GopayAppService/LoginStart"
	GopayAppService_LoginComplete_FullMethodName           = "/gopay_app.GopayAppService/LoginComplete"
	GopayAppService_SignupStart_FullMethodName             = "/gopay_app.GopayAppService/SignupStart"
	GopayAppService_SignupRetry_FullMethodName             = "/gopay_app.GopayAppService/SignupRetry"
	GopayAppService_SignupComplete_FullMethodName          = "/gopay_app.GopayAppService/SignupComplete"
	GopayAppService_CreatePinStart_FullMethodName          = "/gopay_app.GopayAppService/CreatePinStart"
	GopayAppService_CreatePinRetry_FullMethodName          = "/gopay_app.GopayAppService/CreatePinRetry"
	GopayAppService_CreatePinComplete_FullMethodName       = "/gopay_app.GopayAppService/CreatePinComplete"
	GopayAppService_AuthStart_FullMethodName               = "/gopay_app.GopayAppService/AuthStart"
	GopayAppService_AuthComplete_FullMethodName            = "/gopay_app.GopayAppService/AuthComplete"
	GopayAppService_CheckTokenValid_FullMethodName         = "/gopay_app.GopayAppService/CheckTokenValid"
	GopayAppService_ClaimEnvelope_FullMethodName           = "/gopay_app.GopayAppService/ClaimEnvelope"
	GopayAppService_Unlink_FullMethodName                  = "/gopay_app.GopayAppService/Unlink"
	GopayAppService_Status_FullMethodName                  = "/gopay_app.GopayAppService/Status"
	GopayAppService_GetQrId_FullMethodName                 = "/gopay_app.GopayAppService/GetQrId"
	GopayAppService_GetReadyAccountToken_FullMethodName    = "/gopay_app.GopayAppService/GetReadyAccountToken"
	GopayAppService_CheckDeactivation_FullMethodName       = "/gopay_app.GopayAppService/CheckDeactivation"
	GopayAppService_StartGopayPayment_FullMethodName       = "/gopay_app.GopayAppService/StartGopayPayment"
	GopayAppService_CompleteGopayPayment_FullMethodName    = "/gopay_app.GopayAppService/CompleteGopayPayment"
	GopayAppService_ResendGopayPaymentOTP_FullMethodName   = "/gopay_app.GopayAppService/ResendGopayPaymentOTP"
	GopayAppService_ConfirmGopayPayment_FullMethodName     = "/gopay_app.GopayAppService/ConfirmGopayPayment"
	GopayAppService_CancelGopayPayment_FullMethodName      = "/gopay_app.GopayAppService/CancelGopayPayment"
)

// GopayAppServiceClient is the client API for GopayAppService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GopayAppServiceClient interface {
	// GoPay App action/workflow metadata，由 gopay-app 拥有。
	GetActionCatalog(ctx context.Context, in *GetGopayActionCatalogRequest, opts ...grpc.CallOption) (*GetGopayActionCatalogResponse, error)
	// GoPay account state 持久化；gpt-account 不参与。
	GetGopayAccount(ctx context.Context, in *GetGopayAccountRequest, opts ...grpc.CallOption) (*GetGopayAccountResponse, error)
	ListGopayAccounts(ctx context.Context, in *ListGopayAccountsRequest, opts ...grpc.CallOption) (*ListGopayAccountsResponse, error)
	LoadGopayAccountState(ctx context.Context, in *LoadGopayAccountStateRequest, opts ...grpc.CallOption) (*LoadGopayAccountStateResponse, error)
	SaveGopayAccountState(ctx context.Context, in *SaveGopayAccountStateRequest, opts ...grpc.CallOption) (*SaveGopayAccountStateResponse, error)
	DeleteGopayAccount(ctx context.Context, in *DeleteGopayAccountRequest, opts ...grpc.CallOption) (*DeleteGopayAccountResponse, error)
	GetGopayAccountProfile(ctx context.Context, in *GetGopayAccountProfileRequest, opts ...grpc.CallOption) (*GetGopayAccountProfileResponse, error)
	SaveGopayAccountProfile(ctx context.Context, in *SaveGopayAccountProfileRequest, opts ...grpc.CallOption) (*SaveGopayAccountProfileResponse, error)
	// 号码可用性检测；调用方必须先 GenerateDeviceProxy，并把 state_json 传入 CheckPhone。
	GenerateDeviceProxy(ctx context.Context, in *GenerateDeviceProxyRequest, opts ...grpc.CallOption) (*GenerateDeviceProxyResponse, error)
	CheckPhone(ctx context.Context, in *CheckPhoneRequest, opts ...grpc.CallOption) (*CheckPhoneResponse, error)
	// 改手机号（start/retry/complete）
	ChangePhoneStart(ctx context.Context, in *ChangePhoneStartRequest, opts ...grpc.CallOption) (*ChangePhoneStartResponse, error)
	ChangePhoneRetry(ctx context.Context, in *ChangePhoneRetryRequest, opts ...grpc.CallOption) (*ChangePhoneRetryResponse, error)
	ChangePhoneComplete(ctx context.Context, in *ChangePhoneCompleteRequest, opts ...grpc.CallOption) (*ChangePhoneCompleteResponse, error)
	// 注销（两步）
	DeactivateStart(ctx context.Context, in *DeactivateStartRequest, opts ...grpc.CallOption) (*DeactivateStartResponse, error)
	DeactivateComplete(ctx context.Context, in *DeactivateCompleteRequest, opts ...grpc.CallOption) (*DeactivateCompleteResponse, error)
	// 登录（两步）
	LoginStart(ctx context.Context, in *LoginStartRequest, opts ...grpc.CallOption) (*LoginStartResponse, error)
	LoginComplete(ctx context.Context, in *LoginCompleteRequest, opts ...grpc.CallOption) (*LoginCompleteResponse, error)
	// 注册（四步）
	SignupStart(ctx context.Context, in *SignupStartRequest, opts ...grpc.CallOption) (*SignupStartResponse, error)
	SignupRetry(ctx context.Context, in *SignupRetryRequest, opts ...grpc.CallOption) (*SignupRetryResponse, error)
	SignupComplete(ctx context.Context, in *SignupCompleteRequest, opts ...grpc.CallOption) (*SignupCompleteResponse, error)
	CreatePinStart(ctx context.Context, in *CreatePinStartRequest, opts ...grpc.CallOption) (*CreatePinStartResponse, error)
	CreatePinRetry(ctx context.Context, in *CreatePinRetryRequest, opts ...grpc.CallOption) (*CreatePinRetryResponse, error)
	CreatePinComplete(ctx context.Context, in *CreatePinCompleteRequest, opts ...grpc.CallOption) (*CreatePinCompleteResponse, error)
	// 登录 / 注册入口
	AuthStart(ctx context.Context, in *AuthStartRequest, opts ...grpc.CallOption) (*AuthStartResponse, error)
	AuthComplete(ctx context.Context, in *AuthCompleteRequest, opts ...grpc.CallOption) (*AuthCompleteResponse, error)
	CheckTokenValid(ctx context.Context, in *CheckTokenValidRequest, opts ...grpc.CallOption) (*CheckTokenValidResponse, error)
	// GoPay 红包；token 只从 state_json/数据库态获取。
	ClaimEnvelope(ctx context.Context, in *ClaimEnvelopeRequest, opts ...grpc.CallOption) (*ClaimEnvelopeResponse, error)
	// 解绑
	Unlink(ctx context.Context, in *UnlinkRequest, opts ...grpc.CallOption) (*UnlinkResponse, error)
	// 查询
	Status(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*StatusResponse, error)
	GetQrId(ctx context.Context, in *GetQrIdRequest, opts ...grpc.CallOption) (*GetQrIdResponse, error)
	GetReadyAccountToken(ctx context.Context, in *GetReadyAccountTokenRequest, opts ...grpc.CallOption) (*GetReadyAccountTokenResponse, error)
	CheckDeactivation(ctx context.Context, in *CheckDeactivationRequest, opts ...grpc.CallOption) (*CheckDeactivationResponse, error)
	// GoPay payment runtime. GPT prepares checkout/snap_token; gopay-app owns
	// all Midtrans + GoPay linking/payment steps and flow state.
	StartGopayPayment(ctx context.Context, in *StartGopayPaymentRequest, opts ...grpc.CallOption) (*StartGopayPaymentResponse, error)
	CompleteGopayPayment(ctx context.Context, in *CompleteGopayPaymentRequest, opts ...grpc.CallOption) (*GopayPaymentResponse, error)
	ResendGopayPaymentOTP(ctx context.Context, in *ResendGopayPaymentOTPRequest, opts ...grpc.CallOption) (*ResendGopayPaymentOTPResponse, error)
	ConfirmGopayPayment(ctx context.Context, in *ConfirmGopayPaymentRequest, opts ...grpc.CallOption) (*GopayPaymentResponse, error)
	CancelGopayPayment(ctx context.Context, in *CancelGopayPaymentRequest, opts ...grpc.CallOption) (*CancelGopayPaymentResponse, error)
}

type gopayAppServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGopayAppServiceClient(cc grpc.ClientConnInterface) GopayAppServiceClient {
	return &gopayAppServiceClient{cc}
}

func (c *gopayAppServiceClient) GetActionCatalog(ctx context.Context, in *GetGopayActionCatalogRequest, opts ...grpc.CallOption) (*GetGopayActionCatalogResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetGopayActionCatalogResponse)
	err := c.cc.Invoke(ctx, GopayAppService_GetActionCatalog_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gopayAppServiceClient) GetGopayAccount(ctx context.Context, in *GetGopayAccountRequest, opts ...grpc.CallOption) (*GetGopayAccountResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetGopayAccountResponse)
	err := c.cc.Invoke(ctx, GopayAppService_GetGopayAccount_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gopayAppServiceClient) ListGopayAccounts(ctx context.Context, in *ListGopayAccountsRequest, opts ...grpc.CallOption) (*ListGopayAccountsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListGopayAccountsResponse)
	err := c.cc.Invoke(ctx, GopayAppService_ListGopayAccounts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gopayAppServiceClient) LoadGopayAccountState(ctx context.Context, in *LoadGopayAccountStateRequest, opts ...grpc.CallOption) (*LoadGopayAccountStateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LoadGopayAccountStateResponse)
	err := c.cc.Invoke(ctx, GopayAppService_LoadGopayAccountState_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gopayAppServiceClient) SaveGopayAccountState(ctx context.Context, in *SaveGopayAccountStateRequest, opts ...grpc.CallOption) (*SaveGopayAccountStateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SaveGopayAccountStateResponse)
	err := c.cc.Invoke(ctx, GopayAppService_SaveGopayAccountState_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gopayAppServiceClient) DeleteGopayAccount(ctx context.Context, in *DeleteGopayAccountRequest, opts ...grpc.CallOption) (*DeleteGopayAccountResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteGopayAccountResponse)
	err := c.cc.Invoke(ctx, GopayAppService_DeleteGopayAccount_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gopayAppServiceClient) GetGopayAccountProfile(ctx context.Context, in *GetGopayAccountProfileRequest, opts ...grpc.CallOption) (*GetGopayAccountProfileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetGopayAccountProfileResponse)
	err := c.cc.Invoke(ctx, GopayAppService_GetGopayAccountProfile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gopayAppServiceClient) SaveGopayAccountProfile(ctx context.Context, in *SaveGopayAccountProfileRequest, opts ...grpc.CallOption) (*SaveGopayAccountProfileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SaveGopayAccountProfileResponse)
	err := c.cc.Invoke(ctx, GopayAppService_SaveGopayAccountProfile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gopayAppServiceClient) GenerateDeviceProxy(ctx context.Context, in *GenerateDeviceProxyRequest, opts ...grpc.CallOption) (*GenerateDeviceProxyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GenerateDeviceProxyResponse)
	err := c.cc.Invoke(ctx, GopayAppService_GenerateDeviceProxy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gopayAppServiceClient) CheckPhone(ctx context.Context, in *CheckPhoneRequest, opts ...grpc.CallOption) (*CheckPhoneResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckPhoneResponse)
	err := c.cc.Invoke(ctx, GopayAppService_CheckPhone_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gopayAppServiceClient) ChangePhoneStart(ctx context.Context, in *ChangePhoneStartRequest, opts ...grpc.CallOption) (*ChangePhoneStartResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ChangePhoneStartResponse)
	err := c.cc.Invoke(ctx, GopayAppService_ChangePhoneStart_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gopayAppServiceClient) ChangePhoneRetry(ctx context.Context, in *ChangePhoneRetryRequest, opts ...grpc.CallOption) (*ChangePhoneRetryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ChangePhoneRetryResponse)
	err := c.cc.Invoke(ctx, GopayAppService_ChangePhoneRetry_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gopayAppServiceClient) ChangePhoneComplete(ctx context.Context, in *ChangePhoneCompleteRequest, opts ...grpc.CallOption) (*ChangePhoneCompleteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ChangePhoneCompleteResponse)
	err := c.cc.Invoke(ctx, GopayAppService_ChangePhoneComplete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gopayAppServiceClient) DeactivateStart(ctx context.Context, in *DeactivateStartRequest, opts ...grpc.CallOption) (*DeactivateStartResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeactivateStartResponse)
	err := c.cc.Invoke(ctx, GopayAppService_DeactivateStart_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gopayAppServiceClient) DeactivateComplete(ctx context.Context, in *DeactivateCompleteRequest, opts ...grpc.CallOption) (*DeactivateCompleteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeactivateCompleteResponse)
	err := c.cc.Invoke(ctx, GopayAppService_DeactivateComplete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gopayAppServiceClient) LoginStart(ctx context.Context, in *LoginStartRequest, opts ...grpc.CallOption) (*LoginStartResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LoginStartResponse)
	err := c.cc.Invoke(ctx, GopayAppService_LoginStart_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gopayAppServiceClient) LoginComplete(ctx context.Context, in *LoginCompleteRequest, opts ...grpc.CallOption) (*LoginCompleteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LoginCompleteResponse)
	err := c.cc.Invoke(ctx, GopayAppService_LoginComplete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gopayAppServiceClient) SignupStart(ctx context.Context, in *SignupStartRequest, opts ...grpc.CallOption) (*SignupStartResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SignupStartResponse)
	err := c.cc.Invoke(ctx, GopayAppService_SignupStart_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gopayAppServiceClient) SignupRetry(ctx context.Context, in *SignupRetryRequest, opts ...grpc.CallOption) (*SignupRetryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SignupRetryResponse)
	err := c.cc.Invoke(ctx, GopayAppService_SignupRetry_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gopayAppServiceClient) SignupComplete(ctx context.Context, in *SignupCompleteRequest, opts ...grpc.CallOption) (*SignupCompleteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SignupCompleteResponse)
	err := c.cc.Invoke(ctx, GopayAppService_SignupComplete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gopayAppServiceClient) CreatePinStart(ctx context.Context, in *CreatePinStartRequest, opts ...grpc.CallOption) (*CreatePinStartResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreatePinStartResponse)
	err := c.cc.Invoke(ctx, GopayAppService_CreatePinStart_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gopayAppServiceClient) CreatePinRetry(ctx context.Context, in *CreatePinRetryRequest, opts ...grpc.CallOption) (*CreatePinRetryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreatePinRetryResponse)
	err := c.cc.Invoke(ctx, GopayAppService_CreatePinRetry_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gopayAppServiceClient) CreatePinComplete(ctx context.Context, in *CreatePinCompleteRequest, opts ...grpc.CallOption) (*CreatePinCompleteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreatePinCompleteResponse)
	err := c.cc.Invoke(ctx, GopayAppService_CreatePinComplete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gopayAppServiceClient) AuthStart(ctx context.Context, in *AuthStartRequest, opts ...grpc.CallOption) (*AuthStartResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AuthStartResponse)
	err := c.cc.Invoke(ctx, GopayAppService_AuthStart_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gopayAppServiceClient) AuthComplete(ctx context.Context, in *AuthCompleteRequest, opts ...grpc.CallOption) (*AuthCompleteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AuthCompleteResponse)
	err := c.cc.Invoke(ctx, GopayAppService_AuthComplete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gopayAppServiceClient) CheckTokenValid(ctx context.Context, in *CheckTokenValidRequest, opts ...grpc.CallOption) (*CheckTokenValidResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckTokenValidResponse)
	err := c.cc.Invoke(ctx, GopayAppService_CheckTokenValid_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gopayAppServiceClient) ClaimEnvelope(ctx context.Context, in *ClaimEnvelopeRequest, opts ...grpc.CallOption) (*ClaimEnvelopeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ClaimEnvelopeResponse)
	err := c.cc.Invoke(ctx, GopayAppService_ClaimEnvelope_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gopayAppServiceClient) Unlink(ctx context.Context, in *UnlinkRequest, opts ...grpc.CallOption) (*UnlinkResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UnlinkResponse)
	err := c.cc.Invoke(ctx, GopayAppService_Unlink_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gopayAppServiceClient) Status(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*StatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, GopayAppService_Status_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gopayAppServiceClient) GetQrId(ctx context.Context, in *GetQrIdRequest, opts ...grpc.CallOption) (*GetQrIdResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetQrIdResponse)
	err := c.cc.Invoke(ctx, GopayAppService_GetQrId_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gopayAppServiceClient) GetReadyAccountToken(ctx context.Context, in *GetReadyAccountTokenRequest, opts ...grpc.CallOption) (*GetReadyAccountTokenResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetReadyAccountTokenResponse)
	err := c.cc.Invoke(ctx, GopayAppService_GetReadyAccountToken_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gopayAppServiceClient) CheckDeactivation(ctx context.Context, in *CheckDeactivationRequest, opts ...grpc.CallOption) (*CheckDeactivationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckDeactivationResponse)
	err := c.cc.Invoke(ctx, GopayAppService_CheckDeactivation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gopayAppServiceClient) StartGopayPayment(ctx context.Context, in *StartGopayPaymentRequest, opts ...grpc.CallOption) (*StartGopayPaymentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StartGopayPaymentResponse)
	err := c.cc.Invoke(ctx, GopayAppService_StartGopayPayment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gopayAppServiceClient) CompleteGopayPayment(ctx context.Context, in *CompleteGopayPaymentRequest, opts ...grpc.CallOption) (*GopayPaymentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GopayPaymentResponse)
	err := c.cc.Invoke(ctx, GopayAppService_CompleteGopayPayment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gopayAppServiceClient) ResendGopayPaymentOTP(ctx context.Context, in *ResendGopayPaymentOTPRequest, opts ...grpc.CallOption) (*ResendGopayPaymentOTPResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResendGopayPaymentOTPResponse)
	err := c.cc.Invoke(ctx, GopayAppService_ResendGopayPaymentOTP_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gopayAppServiceClient) ConfirmGopayPayment(ctx context.Context, in *ConfirmGopayPaymentRequest, opts ...grpc.CallOption) (*GopayPaymentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GopayPaymentResponse)
	err := c.cc.Invoke(ctx, GopayAppService_ConfirmGopayPayment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gopayAppServiceClient) CancelGopayPayment(ctx context.Context, in *CancelGopayPaymentRequest, opts ...grpc.CallOption) (*CancelGopayPaymentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CancelGopayPaymentResponse)
	err := c.cc.Invoke(ctx, GopayAppService_CancelGopayPayment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GopayAppServiceServer is the server API for GopayAppService service.
// All implementations must embed UnimplementedGopayAppServiceServer
// for forward compatibility.
type GopayAppServiceServer interface {
	// GoPay App action/workflow metadata，由 gopay-app 拥有。
	GetActionCatalog(context.Context, *GetGopayActionCatalogRequest) (*GetGopayActionCatalogResponse, error)
	// GoPay account state 持久化；gpt-account 不参与。
	GetGopayAccount(context.Context, *GetGopayAccountRequest) (*GetGopayAccountResponse, error)
	ListGopayAccounts(context.Context, *ListGopayAccountsRequest) (*ListGopayAccountsResponse, error)
	LoadGopayAccountState(context.Context, *LoadGopayAccountStateRequest) (*LoadGopayAccountStateResponse, error)
	SaveGopayAccountState(context.Context, *SaveGopayAccountStateRequest) (*SaveGopayAccountStateResponse, error)
	DeleteGopayAccount(context.Context, *DeleteGopayAccountRequest) (*DeleteGopayAccountResponse, error)
	GetGopayAccountProfile(context.Context, *GetGopayAccountProfileRequest) (*GetGopayAccountProfileResponse, error)
	SaveGopayAccountProfile(context.Context, *SaveGopayAccountProfileRequest) (*SaveGopayAccountProfileResponse, error)
	// 号码可用性检测；调用方必须先 GenerateDeviceProxy，并把 state_json 传入 CheckPhone。
	GenerateDeviceProxy(context.Context, *GenerateDeviceProxyRequest) (*GenerateDeviceProxyResponse, error)
	CheckPhone(context.Context, *CheckPhoneRequest) (*CheckPhoneResponse, error)
	// 改手机号（start/retry/complete）
	ChangePhoneStart(context.Context, *ChangePhoneStartRequest) (*ChangePhoneStartResponse, error)
	ChangePhoneRetry(context.Context, *ChangePhoneRetryRequest) (*ChangePhoneRetryResponse, error)
	ChangePhoneComplete(context.Context, *ChangePhoneCompleteRequest) (*ChangePhoneCompleteResponse, error)
	// 注销（两步）
	DeactivateStart(context.Context, *DeactivateStartRequest) (*DeactivateStartResponse, error)
	DeactivateComplete(context.Context, *DeactivateCompleteRequest) (*DeactivateCompleteResponse, error)
	// 登录（两步）
	LoginStart(context.Context, *LoginStartRequest) (*LoginStartResponse, error)
	LoginComplete(context.Context, *LoginCompleteRequest) (*LoginCompleteResponse, error)
	// 注册（四步）
	SignupStart(context.Context, *SignupStartRequest) (*SignupStartResponse, error)
	SignupRetry(context.Context, *SignupRetryRequest) (*SignupRetryResponse, error)
	SignupComplete(context.Context, *SignupCompleteRequest) (*SignupCompleteResponse, error)
	CreatePinStart(context.Context, *CreatePinStartRequest) (*CreatePinStartResponse, error)
	CreatePinRetry(context.Context, *CreatePinRetryRequest) (*CreatePinRetryResponse, error)
	CreatePinComplete(context.Context, *CreatePinCompleteRequest) (*CreatePinCompleteResponse, error)
	// 登录 / 注册入口
	AuthStart(context.Context, *AuthStartRequest) (*AuthStartResponse, error)
	AuthComplete(context.Context, *AuthCompleteRequest) (*AuthCompleteResponse, error)
	CheckTokenValid(context.Context, *CheckTokenValidRequest) (*CheckTokenValidResponse, error)
	// GoPay 红包；token 只从 state_json/数据库态获取。
	ClaimEnvelope(context.Context, *ClaimEnvelopeRequest) (*ClaimEnvelopeResponse, error)
	// 解绑
	Unlink(context.Context, *UnlinkRequest) (*UnlinkResponse, error)
	// 查询
	Status(context.Context, *StatusRequest) (*StatusResponse, error)
	GetQrId(context.Context, *GetQrIdRequest) (*GetQrIdResponse, error)
	GetReadyAccountToken(context.Context, *GetReadyAccountTokenRequest) (*GetReadyAccountTokenResponse, error)
	CheckDeactivation(context.Context, *CheckDeactivationRequest) (*CheckDeactivationResponse, error)
	// GoPay payment runtime. GPT prepares checkout/snap_token; gopay-app owns
	// all Midtrans + GoPay linking/payment steps and flow state.
	StartGopayPayment(context.Context, *StartGopayPaymentRequest) (*StartGopayPaymentResponse, error)
	CompleteGopayPayment(context.Context, *CompleteGopayPaymentRequest) (*GopayPaymentResponse, error)
	ResendGopayPaymentOTP(context.Context, *ResendGopayPaymentOTPRequest) (*ResendGopayPaymentOTPResponse, error)
	ConfirmGopayPayment(context.Context, *ConfirmGopayPaymentRequest) (*GopayPaymentResponse, error)
	CancelGopayPayment(context.Context, *CancelGopayPaymentRequest) (*CancelGopayPaymentResponse, error)
	mustEmbedUnimplementedGopayAppServiceServer()
}

// UnimplementedGopayAppServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGopayAppServiceServer struct{}

func (UnimplementedGopayAppServiceServer) GetActionCatalog(context.Context, *GetGopayActionCatalogRequest) (*GetGopayActionCatalogResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetActionCatalog not implemented")
}
func (UnimplementedGopayAppServiceServer) GetGopayAccount(context.Context, *GetGopayAccountRequest) (*GetGopayAccountResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetGopayAccount not implemented")
}
func (UnimplementedGopayAppServiceServer) ListGopayAccounts(context.Context, *ListGopayAccountsRequest) (*ListGopayAccountsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListGopayAccounts not implemented")
}
func (UnimplementedGopayAppServiceServer) LoadGopayAccountState(context.Context, *LoadGopayAccountStateRequest) (*LoadGopayAccountStateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LoadGopayAccountState not implemented")
}
func (UnimplementedGopayAppServiceServer) SaveGopayAccountState(context.Context, *SaveGopayAccountStateRequest) (*SaveGopayAccountStateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SaveGopayAccountState not implemented")
}
func (UnimplementedGopayAppServiceServer) DeleteGopayAccount(context.Context, *DeleteGopayAccountRequest) (*DeleteGopayAccountResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteGopayAccount not implemented")
}
func (UnimplementedGopayAppServiceServer) GetGopayAccountProfile(context.Context, *GetGopayAccountProfileRequest) (*GetGopayAccountProfileResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetGopayAccountProfile not implemented")
}
func (UnimplementedGopayAppServiceServer) SaveGopayAccountProfile(context.Context, *SaveGopayAccountProfileRequest) (*SaveGopayAccountProfileResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SaveGopayAccountProfile not implemented")
}
func (UnimplementedGopayAppServiceServer) GenerateDeviceProxy(context.Context, *GenerateDeviceProxyRequest) (*GenerateDeviceProxyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GenerateDeviceProxy not implemented")
}
func (UnimplementedGopayAppServiceServer) CheckPhone(context.Context, *CheckPhoneRequest) (*CheckPhoneResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckPhone not implemented")
}
func (UnimplementedGopayAppServiceServer) ChangePhoneStart(context.Context, *ChangePhoneStartRequest) (*ChangePhoneStartResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ChangePhoneStart not implemented")
}
func (UnimplementedGopayAppServiceServer) ChangePhoneRetry(context.Context, *ChangePhoneRetryRequest) (*ChangePhoneRetryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ChangePhoneRetry not implemented")
}
func (UnimplementedGopayAppServiceServer) ChangePhoneComplete(context.Context, *ChangePhoneCompleteRequest) (*ChangePhoneCompleteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ChangePhoneComplete not implemented")
}
func (UnimplementedGopayAppServiceServer) DeactivateStart(context.Context, *DeactivateStartRequest) (*DeactivateStartResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeactivateStart not implemented")
}
func (UnimplementedGopayAppServiceServer) DeactivateComplete(context.Context, *DeactivateCompleteRequest) (*DeactivateCompleteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeactivateComplete not implemented")
}
func (UnimplementedGopayAppServiceServer) LoginStart(context.Context, *LoginStartRequest) (*LoginStartResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LoginStart not implemented")
}
func (UnimplementedGopayAppServiceServer) LoginComplete(context.Context, *LoginCompleteRequest) (*LoginCompleteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LoginComplete not implemented")
}
func (UnimplementedGopayAppServiceServer) SignupStart(context.Context, *SignupStartRequest) (*SignupStartResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SignupStart not implemented")
}
func (UnimplementedGopayAppServiceServer) SignupRetry(context.Context, *SignupRetryRequest) (*SignupRetryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SignupRetry not implemented")
}
func (UnimplementedGopayAppServiceServer) SignupComplete(context.Context, *SignupCompleteRequest) (*SignupCompleteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SignupComplete not implemented")
}
func (UnimplementedGopayAppServiceServer) CreatePinStart(context.Context, *CreatePinStartRequest) (*CreatePinStartResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreatePinStart not implemented")
}
func (UnimplementedGopayAppServiceServer) CreatePinRetry(context.Context, *CreatePinRetryRequest) (*CreatePinRetryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreatePinRetry not implemented")
}
func (UnimplementedGopayAppServiceServer) CreatePinComplete(context.Context, *CreatePinCompleteRequest) (*CreatePinCompleteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreatePinComplete not implemented")
}
func (UnimplementedGopayAppServiceServer) AuthStart(context.Context, *AuthStartRequest) (*AuthStartResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AuthStart not implemented")
}
func (UnimplementedGopayAppServiceServer) AuthComplete(context.Context, *AuthCompleteRequest) (*AuthCompleteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AuthComplete not implemented")
}
func (UnimplementedGopayAppServiceServer) CheckTokenValid(context.Context, *CheckTokenValidRequest) (*CheckTokenValidResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckTokenValid not implemented")
}
func (UnimplementedGopayAppServiceServer) ClaimEnvelope(context.Context, *ClaimEnvelopeRequest) (*ClaimEnvelopeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ClaimEnvelope not implemented")
}
func (UnimplementedGopayAppServiceServer) Unlink(context.Context, *UnlinkRequest) (*UnlinkResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Unlink not implemented")
}
func (UnimplementedGopayAppServiceServer) Status(context.Context, *StatusRequest) (*StatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Status not implemented")
}
func (UnimplementedGopayAppServiceServer) GetQrId(context.Context, *GetQrIdRequest) (*GetQrIdResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetQrId not implemented")
}
func (UnimplementedGopayAppServiceServer) GetReadyAccountToken(context.Context, *GetReadyAccountTokenRequest) (*GetReadyAccountTokenResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetReadyAccountToken not implemented")
}
func (UnimplementedGopayAppServiceServer) CheckDeactivation(context.Context, *CheckDeactivationRequest) (*CheckDeactivationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckDeactivation not implemented")
}
func (UnimplementedGopayAppServiceServer) StartGopayPayment(context.Context, *StartGopayPaymentRequest) (*StartGopayPaymentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartGopayPayment not implemented")
}
func (UnimplementedGopayAppServiceServer) CompleteGopayPayment(context.Context, *CompleteGopayPaymentRequest) (*GopayPaymentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CompleteGopayPayment not implemented")
}
func (UnimplementedGopayAppServiceServer) ResendGopayPaymentOTP(context.Context, *ResendGopayPaymentOTPRequest) (*ResendGopayPaymentOTPResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ResendGopayPaymentOTP not implemented")
}
func (UnimplementedGopayAppServiceServer) ConfirmGopayPayment(context.Context, *ConfirmGopayPaymentRequest) (*GopayPaymentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ConfirmGopayPayment not implemented")
}
func (UnimplementedGopayAppServiceServer) CancelGopayPayment(context.Context, *CancelGopayPaymentRequest) (*CancelGopayPaymentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CancelGopayPayment not implemented")
}
func (UnimplementedGopayAppServiceServer) mustEmbedUnimplementedGopayAppServiceServer() {}
func (UnimplementedGopayAppServiceServer) testEmbeddedByValue()                         {}

// UnsafeGopayAppServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GopayAppServiceServer will
// result in compilation errors.
type UnsafeGopayAppServiceServer interface {
	mustEmbedUnimplementedGopayAppServiceServer()
}

func RegisterGopayAppServiceServer(s grpc.ServiceRegistrar, srv GopayAppServiceServer) {
	// If the following call pancis, it indicates UnimplementedGopayAppServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GopayAppService_ServiceDesc, srv)
}

func _GopayAppService_GetActionCatalog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetGopayActionCatalogRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GopayAppServiceServer).GetActionCatalog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GopayAppService_GetActionCatalog_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GopayAppServiceServer).GetActionCatalog(ctx, req.(*GetGopayActionCatalogRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GopayAppService_GetGopayAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetGopayAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GopayAppServiceServer).GetGopayAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GopayAppService_GetGopayAccount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GopayAppServiceServer).GetGopayAccount(ctx, req.(*GetGopayAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GopayAppService_ListGopayAccounts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListGopayAccountsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GopayAppServiceServer).ListGopayAccounts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GopayAppService_ListGopayAccounts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GopayAppServiceServer).ListGopayAccounts(ctx, req.(*ListGopayAccountsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GopayAppService_LoadGopayAccountState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoadGopayAccountStateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GopayAppServiceServer).LoadGopayAccountState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GopayAppService_LoadGopayAccountState_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GopayAppServiceServer).LoadGopayAccountState(ctx, req.(*LoadGopayAccountStateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GopayAppService_SaveGopayAccountState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaveGopayAccountStateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GopayAppServiceServer).SaveGopayAccountState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GopayAppService_SaveGopayAccountState_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GopayAppServiceServer).SaveGopayAccountState(ctx, req.(*SaveGopayAccountStateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GopayAppService_DeleteGopayAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteGopayAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GopayAppServiceServer).DeleteGopayAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GopayAppService_DeleteGopayAccount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GopayAppServiceServer).DeleteGopayAccount(ctx, req.(*DeleteGopayAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GopayAppService_GetGopayAccountProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetGopayAccountProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GopayAppServiceServer).GetGopayAccountProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GopayAppService_GetGopayAccountProfile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GopayAppServiceServer).GetGopayAccountProfile(ctx, req.(*GetGopayAccountProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GopayAppService_SaveGopayAccountProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaveGopayAccountProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GopayAppServiceServer).SaveGopayAccountProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GopayAppService_SaveGopayAccountProfile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GopayAppServiceServer).SaveGopayAccountProfile(ctx, req.(*SaveGopayAccountProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GopayAppService_GenerateDeviceProxy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenerateDeviceProxyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GopayAppServiceServer).GenerateDeviceProxy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GopayAppService_GenerateDeviceProxy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GopayAppServiceServer).GenerateDeviceProxy(ctx, req.(*GenerateDeviceProxyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GopayAppService_CheckPhone_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckPhoneRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GopayAppServiceServer).CheckPhone(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GopayAppService_CheckPhone_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GopayAppServiceServer).CheckPhone(ctx, req.(*CheckPhoneRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GopayAppService_ChangePhoneStart_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChangePhoneStartRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GopayAppServiceServer).ChangePhoneStart(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GopayAppService_ChangePhoneStart_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GopayAppServiceServer).ChangePhoneStart(ctx, req.(*ChangePhoneStartRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GopayAppService_ChangePhoneRetry_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChangePhoneRetryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GopayAppServiceServer).ChangePhoneRetry(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GopayAppService_ChangePhoneRetry_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GopayAppServiceServer).ChangePhoneRetry(ctx, req.(*ChangePhoneRetryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GopayAppService_ChangePhoneComplete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChangePhoneCompleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GopayAppServiceServer).ChangePhoneComplete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GopayAppService_ChangePhoneComplete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GopayAppServiceServer).ChangePhoneComplete(ctx, req.(*ChangePhoneCompleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GopayAppService_DeactivateStart_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeactivateStartRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GopayAppServiceServer).DeactivateStart(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GopayAppService_DeactivateStart_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GopayAppServiceServer).DeactivateStart(ctx, req.(*DeactivateStartRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GopayAppService_DeactivateComplete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeactivateCompleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GopayAppServiceServer).DeactivateComplete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GopayAppService_DeactivateComplete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GopayAppServiceServer).DeactivateComplete(ctx, req.(*DeactivateCompleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GopayAppService_LoginStart_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginStartRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GopayAppServiceServer).LoginStart(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GopayAppService_LoginStart_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GopayAppServiceServer).LoginStart(ctx, req.(*LoginStartRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GopayAppService_LoginComplete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginCompleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GopayAppServiceServer).LoginComplete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GopayAppService_LoginComplete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GopayAppServiceServer).LoginComplete(ctx, req.(*LoginCompleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GopayAppService_SignupStart_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SignupStartRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GopayAppServiceServer).SignupStart(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GopayAppService_SignupStart_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GopayAppServiceServer).SignupStart(ctx, req.(*SignupStartRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GopayAppService_SignupRetry_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SignupRetryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GopayAppServiceServer).SignupRetry(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GopayAppService_SignupRetry_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GopayAppServiceServer).SignupRetry(ctx, req.(*SignupRetryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GopayAppService_SignupComplete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SignupCompleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GopayAppServiceServer).SignupComplete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GopayAppService_SignupComplete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GopayAppServiceServer).SignupComplete(ctx, req.(*SignupCompleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GopayAppService_CreatePinStart_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatePinStartRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GopayAppServiceServer).CreatePinStart(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GopayAppService_CreatePinStart_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GopayAppServiceServer).CreatePinStart(ctx, req.(*CreatePinStartRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GopayAppService_CreatePinRetry_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatePinRetryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GopayAppServiceServer).CreatePinRetry(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GopayAppService_CreatePinRetry_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GopayAppServiceServer).CreatePinRetry(ctx, req.(*CreatePinRetryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GopayAppService_CreatePinComplete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatePinCompleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GopayAppServiceServer).CreatePinComplete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GopayAppService_CreatePinComplete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GopayAppServiceServer).CreatePinComplete(ctx, req.(*CreatePinCompleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GopayAppService_AuthStart_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthStartRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GopayAppServiceServer).AuthStart(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GopayAppService_AuthStart_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GopayAppServiceServer).AuthStart(ctx, req.(*AuthStartRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GopayAppService_AuthComplete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthCompleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GopayAppServiceServer).AuthComplete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GopayAppService_AuthComplete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GopayAppServiceServer).AuthComplete(ctx, req.(*AuthCompleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GopayAppService_CheckTokenValid_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckTokenValidRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GopayAppServiceServer).CheckTokenValid(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GopayAppService_CheckTokenValid_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GopayAppServiceServer).CheckTokenValid(ctx, req.(*CheckTokenValidRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GopayAppService_ClaimEnvelope_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClaimEnvelopeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GopayAppServiceServer).ClaimEnvelope(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GopayAppService_ClaimEnvelope_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GopayAppServiceServer).ClaimEnvelope(ctx, req.(*ClaimEnvelopeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GopayAppService_Unlink_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnlinkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GopayAppServiceServer).Unlink(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GopayAppService_Unlink_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GopayAppServiceServer).Unlink(ctx, req.(*UnlinkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GopayAppService_Status_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GopayAppServiceServer).Status(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GopayAppService_Status_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GopayAppServiceServer).Status(ctx, req.(*StatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GopayAppService_GetQrId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetQrIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GopayAppServiceServer).GetQrId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GopayAppService_GetQrId_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GopayAppServiceServer).GetQrId(ctx, req.(*GetQrIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GopayAppService_GetReadyAccountToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetReadyAccountTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GopayAppServiceServer).GetReadyAccountToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GopayAppService_GetReadyAccountToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GopayAppServiceServer).GetReadyAccountToken(ctx, req.(*GetReadyAccountTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GopayAppService_CheckDeactivation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckDeactivationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GopayAppServiceServer).CheckDeactivation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GopayAppService_CheckDeactivation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GopayAppServiceServer).CheckDeactivation(ctx, req.(*CheckDeactivationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GopayAppService_StartGopayPayment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartGopayPaymentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GopayAppServiceServer).StartGopayPayment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GopayAppService_StartGopayPayment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GopayAppServiceServer).StartGopayPayment(ctx, req.(*StartGopayPaymentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GopayAppService_CompleteGopayPayment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CompleteGopayPaymentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GopayAppServiceServer).CompleteGopayPayment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GopayAppService_CompleteGopayPayment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GopayAppServiceServer).CompleteGopayPayment(ctx, req.(*CompleteGopayPaymentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GopayAppService_ResendGopayPaymentOTP_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResendGopayPaymentOTPRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GopayAppServiceServer).ResendGopayPaymentOTP(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GopayAppService_ResendGopayPaymentOTP_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GopayAppServiceServer).ResendGopayPaymentOTP(ctx, req.(*ResendGopayPaymentOTPRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GopayAppService_ConfirmGopayPayment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfirmGopayPaymentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GopayAppServiceServer).ConfirmGopayPayment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GopayAppService_ConfirmGopayPayment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GopayAppServiceServer).ConfirmGopayPayment(ctx, req.(*ConfirmGopayPaymentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GopayAppService_CancelGopayPayment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelGopayPaymentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GopayAppServiceServer).CancelGopayPayment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GopayAppService_CancelGopayPayment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GopayAppServiceServer).CancelGopayPayment(ctx, req.(*CancelGopayPaymentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GopayAppService_ServiceDesc is the grpc.ServiceDesc for GopayAppService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GopayAppService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "gopay_app.GopayAppService",
	HandlerType: (*GopayAppServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetActionCatalog",
			Handler:    _GopayAppService_GetActionCatalog_Handler,
		},
		{
			MethodName: "GetGopayAccount",
			Handler:    _GopayAppService_GetGopayAccount_Handler,
		},
		{
			MethodName: "ListGopayAccounts",
			Handler:    _GopayAppService_ListGopayAccounts_Handler,
		},
		{
			MethodName: "LoadGopayAccountState",
			Handler:    _GopayAppService_LoadGopayAccountState_Handler,
		},
		{
			MethodName: "SaveGopayAccountState",
			Handler:    _GopayAppService_SaveGopayAccountState_Handler,
		},
		{
			MethodName: "DeleteGopayAccount",
			Handler:    _GopayAppService_DeleteGopayAccount_Handler,
		},
		{
			MethodName: "GetGopayAccountProfile",
			Handler:    _GopayAppService_GetGopayAccountProfile_Handler,
		},
		{
			MethodName: "SaveGopayAccountProfile",
			Handler:    _GopayAppService_SaveGopayAccountProfile_Handler,
		},
		{
			MethodName: "GenerateDeviceProxy",
			Handler:    _GopayAppService_GenerateDeviceProxy_Handler,
		},
		{
			MethodName: "CheckPhone",
			Handler:    _GopayAppService_CheckPhone_Handler,
		},
		{
			MethodName: "ChangePhoneStart",
			Handler:    _GopayAppService_ChangePhoneStart_Handler,
		},
		{
			MethodName: "ChangePhoneRetry",
			Handler:    _GopayAppService_ChangePhoneRetry_Handler,
		},
		{
			MethodName: "ChangePhoneComplete",
			Handler:    _GopayAppService_ChangePhoneComplete_Handler,
		},
		{
			MethodName: "DeactivateStart",
			Handler:    _GopayAppService_DeactivateStart_Handler,
		},
		{
			MethodName: "DeactivateComplete",
			Handler:    _GopayAppService_DeactivateComplete_Handler,
		},
		{
			MethodName: "LoginStart",
			Handler:    _GopayAppService_LoginStart_Handler,
		},
		{
			MethodName: "LoginComplete",
			Handler:    _GopayAppService_LoginComplete_Handler,
		},
		{
			MethodName: "SignupStart",
			Handler:    _GopayAppService_SignupStart_Handler,
		},
		{
			MethodName: "SignupRetry",
			Handler:    _GopayAppService_SignupRetry_Handler,
		},
		{
			MethodName: "SignupComplete",
			Handler:    _GopayAppService_SignupComplete_Handler,
		},
		{
			MethodName: "CreatePinStart",
			Handler:    _GopayAppService_CreatePinStart_Handler,
		},
		{
			MethodName: "CreatePinRetry",
			Handler:    _GopayAppService_CreatePinRetry_Handler,
		},
		{
			MethodName: "CreatePinComplete",
			Handler:    _GopayAppService_CreatePinComplete_Handler,
		},
		{
			MethodName: "AuthStart",
			Handler:    _GopayAppService_AuthStart_Handler,
		},
		{
			MethodName: "AuthComplete",
			Handler:    _GopayAppService_AuthComplete_Handler,
		},
		{
			MethodName: "CheckTokenValid",
			Handler:    _GopayAppService_CheckTokenValid_Handler,
		},
		{
			MethodName: "ClaimEnvelope",
			Handler:    _GopayAppService_ClaimEnvelope_Handler,
		},
		{
			MethodName: "Unlink",
			Handler:    _GopayAppService_Unlink_Handler,
		},
		{
			MethodName: "Status",
			Handler:    _GopayAppService_Status_Handler,
		},
		{
			MethodName: "GetQrId",
			Handler:    _GopayAppService_GetQrId_Handler,
		},
		{
			MethodName: "GetReadyAccountToken",
			Handler:    _GopayAppService_GetReadyAccountToken_Handler,
		},
		{
			MethodName: "CheckDeactivation",
			Handler:    _GopayAppService_CheckDeactivation_Handler,
		},
		{
			MethodName: "StartGopayPayment",
			Handler:    _GopayAppService_StartGopayPayment_Handler,
		},
		{
			MethodName: "CompleteGopayPayment",
			Handler:    _GopayAppService_CompleteGopayPayment_Handler,
		},
		{
			MethodName: "ResendGopayPaymentOTP",
			Handler:    _GopayAppService_ResendGopayPaymentOTP_Handler,
		},
		{
			MethodName: "ConfirmGopayPayment",
			Handler:    _GopayAppService_ConfirmGopayPayment_Handler,
		},
		{
			MethodName: "CancelGopayPayment",
			Handler:    _GopayAppService_CancelGopayPayment_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "gopay_app.proto",
}
